apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp-frontend
  template:
    metadata:
      labels:
        app: blogapp-frontend
    spec:
      containers:
        - name: frontend
          image: sanuvi5043/blogapp-frontend:latest
          ports:
            - containerPort: 80       # change from 3000 → 80
          env:
            - name: BACKEND_URL
              value: "http://blogapp-backend:5000"