---
- name: Stop and remove old containers
  docker_container:
    name: "{{ item }}"
    state: absent
    force_kill: true
  loop:
    - blogapp_front
    - blogapp_back

- name: Pull latest backend image
  docker_image:
    name: sanuvi5043/blogapp-backend
    tag: latest
    source: pull

- name: Run backend container
  docker_container:
    name: blogapp_back
    image: sanuvi5043/blogapp-backend:latest
    state: started
    restart_policy: always
    published_ports:
      - "5000:5000"

- name: Pull latest frontend image
  docker_image:
    name: sanuvi5043/blogapp-frontend
    tag: latest
    source: pull

- name: Run frontend container
  docker_container:
    name: blogapp_front
    image: sanuvi5043/blogapp-frontend:latest
    state: started
    restart_policy: always
    published_ports:
      - "3000:3000"